export const adminOptionsState = {
   usuariosModal              : false,
   addUserModal               : false,
   userEditModal              : false,
   reRender                   : false,
   isNewUser                  : false,
   switchAsistencia           : true,
   switchCalificacionesLeer   : true,
   switchCalificacionesEditar : true,
   switchUsuario              : true,
   switchPassword             : true,
   switchRole                 : true,
   user                       : null,
   password                   : null,
   role                       : 'Seleccione tipo de usuario',
   selectedUser               : '',
   dataUser                   : {},
   dataUsuarios               : [],
}
