const mongoose = require('mongoose')

const {Schema} = mongoose

const matriculaSchema = new Schema({
   estado: {type: String,require:true},
   nDniAlumno: {type: String,require:true},
   tipo: {type: String, require:true},
   apellido: {type: String, require:true},
   nombre: {type:String,require:true},
   sexo: {type:String,require:true},
   fechaNacimiento: {type:String,require:true},
   lugarNacimiento: {type:String,require:true},
   nacionalidad: {type:String,require:true},
   provinciaNacimiento: {type:String,require:true},
   email: {type:String,require:true},
   cuil:{type:String,require:true},
   nroLegajo: {type:String,require:true},
   calle: {type:String,require:true},
   nro: {type:String,require:true},
   barrio: {type:String,require:true},
   localidad: {type:String,require:true},
   provincia: {type:String,require:true},
   telFijo:{type:String,require:true},
   telCelular: {type:String,require:true},
   nivel: {type: String, require:true},
   grado: {type: Number,require:true},
   division: {type: String, require:true},
   denominacion: {type:String,require:true},
   apellidoTutor:{type:String,require:true},
   nombreTutor: {type:String,require:true},
   dniTutor: {type:String,require:true},
   profesionTutor: {type:String,require:true},
   relacionTutor: {type:String,require:true},
   emailTutor: {type:String,require:true},
   examenVisual: {type:String,require:true},
   certSalud:{type:String,require:true},
   certBucoDental: {type:String,require:true},
   vacunasAlDia:{type:String,require:true},
   antivariolica: {type:String,require:true},
   bcg:{type:String,require:true},
   triple: {type:String,require:true},
   doble: {type:String,require:true},
   sabin: {type:String,require:true},
   antiSarampion: {type:String,require:true}, 
   otras1: {type:String,require:true},
   otras2: {type:String,require:true},
   ingreso: {type:String,require:true},
   egreso: {type:String,require:true},
   observaciones: {type:Array,require:true},
   registro: {type:Array,require:true},
},{collection: 'Matricula'});

module.exports = mongoose.model('Matricula', matriculaSchema)
